sudo: required
language: node_js
node_js:
  - "6"
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - npm run test1
#  - npm run e2e #got this on travis: E/launcher - unknown error: Chrome version must be >= 52.0.2743.0